# Load all controllers that use #[Route(...)] attributes
controllers:
    resource: ../src/Controller/
    type: attribute

# Optional: make "/" redirect to the home page
app_root_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults: { route: 'app_home', permanent: false }
