# config/routes.yaml
controllers:
    resource: ../src/Controller/
    type: attribute

app_root_redirect:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_home
        permanent: false   # 302 (temporaire). Mets true pour 301.
